### ISSUE TITLE
psiturk 2.1.1 on pip not identical to master

### ISSUE THREAD

**Issue by RoyalTS** [NYUCCL/psiTurk#168]
Various places in the current master branch (e.g. psiturk/version.py and the README) claim that the psiturk version in that branch is 2.1.1. However, what's in master is not identical to the version 2.1.1. one gets when installing via pip. I just ran into [this old bug](https://github.com/NYUCCL/psiTurk/commit/435e3c4d5c435565fed0cd729a3daa978304636a) that was fixed in master months ago. Perhaps you guys should bump the version and build a new pip package?

**Comment by gureckis** [comment]
oh, good point, I was in the habit of updating pip when there is a major update, but these small patches don't trigger a change.  will update pip for now manually and see if we can set up some kind of automatic monitoring

**Comment by RoyalTS** [comment]
Sounds good! This sounds like it could be helpful: http://docs.travis-ci.com/user/deployment/pypi/

**Comment by gureckis** [comment]
I bumped version number to 2.1.2 to include some recent minor fixes and uploaded to pypi.  Didn't establish the automatic monitoring, but will try to stay on top of this.  One solution is to only allow incoming pull requests to go to dev so that dev matures and is infrequently updated to master (along with a pip deployment).
