### ISSUE TITLE
worker assignmentID is not unique?

### ISSUE THREAD

**Issue by infiniteline** [NYUCCL/psiTurk#184]
Hey all,

  I just ran a small experiment and noticed that two workers had an identical value in the assignmentID field. This is a problem when trying to reject workers as you have to use the assignmentID to reject. In my case, one worker did not complete the experiment while the other did. I'm assuming that assignmentID is supposed to be unique?

**Comment by jacob-lee** [comment]
I have experienced this issue. Assignment IDs are not unique. AssignmentId/WorkerId pairs are unique if you do not allow a worker to return and then accept the same HIT. The assignment ID is provided by Amazon. It appears that if the assignment is returned or otherwise not completed, the assignment id is given to the next worker who accepts.

The psiturk command line tool only presents the completed HITs. HITs that were returned don't have to/cannot be rejected. Hence, the only issue is if you are doing your own database queries to determine whom to have rejected, in which case all you should have to do is check whether it was completed.

**Comment by infiniteline** [comment]
Thanks for the information, Jacob. Yes, I was looking through the database entries manually and trying to reject the ones that were not complete. I didn't think Mechanical Turk was going to make it *that* easy for me!  ;)    Thanks again for your response.
