### ISSUE TITLE
Improve performance of amt_services.py

### ISSUE THREAD

**Issue by fredcallaway** [NYUCCL/psiTurk#287]
For a large lab with a heavily used account, the shell is painfully slow. The current implementation frequently calls the `MTurkServices.get_workers` (likely a time-intensive function) when a more specific API call would suffice. For example, when listing workers for a single HIT `PsiturkNetworkShell.worker_list(chosen_hit=XXX)`, we first pull every worker from any HIT, and then filter out the ones not from the chosen hit. Wouldn't it be faster to use the `MTurkConnection.get_assignments(hit_id)` method from `boto`?

**Comment by deargle** [comment]
Likely so. Care to refactor for the `chosen_hit` situation? [Link for posterity](https://github.com/NYUCCL/psiTurk/blob/790d94cf328abcbb253c0dbbc42b8fe898e0488c/psiturk/psiturk_shell.py#L668). PRs welcome! Although, warning, testing and integration is slow.

**Comment by deargle** [comment]
By the way, all boto calls have been ultra slow for me for the past week. Not sure why.

**Comment by deargle** [comment]
... upon further inspection, I think I'm actually experiencing slowness for the same reason you describe -- because all workers are always queried. And yes, this is a slow operation. We can only request 100 at a time.

I just [pushed a commit][2c73a7997c119e41dd91ec9da2159fff8991dbbb) that makes `worker_list` respect `chosen_hit`, if present. I'm going to do `worker_approve` next.

**Comment by deargle** [comment]
I just pushed a few more commits to master that make `worker_approve` and `worker_bonus` act smarter when given a chosen_hit or when given only one assignmentid (for the latter, added a new function to amt_services called `get_worker` that only pulls one worker instead of pulling all for a given status and/or hitid)
