### ISSUE TITLE
[question] a little confused

### ISSUE THREAD

**Issue by AlJohri** [NYUCCL/psiTurk#302]
hi! i'm evaluating whether psiTurk will work for some experiments I'm about to run. I've tried reading all the docs on https://psiturk.org/ but I'm still pretty confused as to how it works.

1. what exactly is an Ad in terms of MTurk? is it just a HIT? that redirects you to the experiment running on your local computer? if so, why not present the task directly instead of going through an ad?

2. what is the local server (or a server in general) needed for? it looks like the [ExternalQuestion](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html) asks you to post the resulting data to mturk's servers so a server shouldn't be necessary? hosting the external question iframe on s3 or github pages could be sufficient?

apologies if this is the wrong place to ask, just a bit confused. I'm a big fan of the downloadable/repeatable experiments so I'm hoping psiTurk might work for me. thanks!

**Comment by deargle** [comment]
Hi Aljohri,

> 1. what exactly is an Ad in terms of MTurk? is it just a HIT? that redirects you to the experiment running on your local computer? if so, why not present the task directly instead of going through an ad?

To create an ExternalHit on mturk, you make a call with some general descriptive information like reward amount, number of assignments for the hit, duration of the hit, and _a link to your ad_. You don't actually upload any data to mturk, just metadata like that. The "ad" has rules set by mturk -- one being that it must be served over https. The "ad" is the url that will load into an iframe on mturk when (1) a worker is looking at your hit but has not yet accepted it and (2) immediately once a worker has accepted your hit. Your ad is passed special URL parameters by mturk that tell you whether or not the assignment has been "accepted" yet or if it is just being previewed. 

So, yes, you can host an ad anywhere, even in a place entirely different from your study, as long as the ad is https.

Where the worker goes after they accept your hit is up to you -- you just provide a link on the "accepted" version of your ad that takes workers where they need to do. The link on that page should pass along the url parameters that mturk gave you, such as workerid, assignmentid, hitid, or some combination of those (can't remember).

> 2. what is the local server (or a server in general) needed for? it looks like the ExternalQuestion asks you to post the resulting data to mturk's servers so a server shouldn't be necessary? hosting the external question iframe on s3 or github pages could be sufficient?

psiturk provides a server that hosts the interaction between your worker and your study. the psiturk.js code sends data to the server, which in turn saves it to your database. The server also interacts with the database to log your workers, keep track of their 'status' in your study, determine their assigned treatment condition, and to block them if they have already taken one of your studies or if they quit in the middle of one of your studies. If you want your study to interface with a database, you need a server.

The "local" server is one that can run on your-computer-only but that isn't necessarily accessible to the outside world. I use a local server for developing my studies.

Then, when you run your study, you install psiturk on someplace that has a publicly-accessible ip, and 'run' the server. Running the server makes it so that you can actually "serve" your study's pages (which are dynamically generated). Running the server also sets up an api that the psiturk.js calls to save the data, and set/update worker statuses. You probably saw in the docs that it's not a good idea to put a psiturk server directly accessible from the public internet -- you ideally need a reverse proxy server in front of it, like nginx. Even if you use nginx, it still passes requests to your psiturk server (which is just a Gunicorn server that runs Flask routes)

I run all my studies, including my "ads", on heroku, which provides free no-config https. You also have an option of using the "psiturk ad server", which you saw in the docs, which is an answer to the problem of "I want to run an mturk study but I don't know how to config https pls halp". The psiturk ad server hosts your ad, then redirects workers to your publicly-accessible-but-not-necessarily-https url for the rest of the study. Heads up though, the psiturk ad server has had intermittent unreliability due to periodic heavy loads. And if the ad doesn't load, no one can take your study. My general advice is to host your own ad if you can manage.

Does that help?

**Comment by AlJohri** [comment]
1. Okay this makes sense- that's a nifty idea to switch the interface before the worker accepts an assignment.

2. Is there a benefit to running the study in this way via a server/db instead of POSTing the data back to MTurk and downloading the data from there when the Hits are completed? That way you keep MTurk's API as the source of truth? I've done this once before with a regular QuestionForm and I'll admit it wasn't a _great_ experience getting the data out of MTurk's API, but it worked. Just curious if there's some other benefits I'm not thinking of to using a database vs storing the data in MTurk itself.

>heroku
that's a good idea, I'll definitely do that if I go the psiTurk route

>block them if they have already taken one of your studies
doesn't mturk automatically do this? or is that only if they've already participated in this _specific_ study?

Thanks for the detailed response! I really appreciate it.

**Comment by deargle** [comment]
> 1. Okay this makes sense- that's a nifty idea to switch the interface before the worker accepts an assignment.

Not psiturk's idea, it's just the way mturk works. They _tell_ you to do that.

> 2. Is there a benefit to running the study in this way via a server/db instead of POSTing the data back to MTurk and downloading the data from there when the Hits are completed? That way you keep MTurk's API as the source of truth? I've done this once before with a regular QuestionForm and I'll admit it wasn't a great experience getting the data out of MTurk's API, but it worked. Just curious if there's some other benefits I'm not thinking of to using a database vs storing the data in MTurk itself.

You're thinking about doing a db-less experiment, pure javascript, post a json array of data to mturk when you're done? Theoretically possible if you're doing simple random assignment. One concern is that you could _not_ block repeats, you could not flag quitters, you could not do balanced random assignment like psiturk does (not necessarily a loss), you could not easily do bonus calculation and flagging of who has already been paid a bonus, but those things aside, sure, I guess you could go sans db. 

But no, you could _not_ block repeats without a db. Here's the thing. Mturk prevents someone from taking _more than one assignment_ for any given HIT, but there is no mturk block against taking one assignment from multiple HITs, even if they're for the same study. Sure, you're welcome to post a HIT with 1,000 assignments available if that's the _n_ you need. But you'd better hope you don't have a v2 of your experiment. Also, you pay 40% commission for posting any HIT with >9 assignments available, versus 20% for <=9. I'm a scrooge, I post dozens of hits with <=9 assignments. As long as they all have the same name (or something like that) all HITs and their associated assignments are grouped on the mturk dashboard. If someone goes in to take the study and there's already a record for them in the db, psiturk will present them with an error message saying "go away".

**Comment by AlJohri** [comment]
I'm going to look more into the "block repeats", ">9 assignments", and "40% commission" part you mentioned. I wasn't aware of any of that before. Might have wasted a lot of money in past experiments...

thank you for the prompt and thorough responses! this was super helpful!

**Comment by AlJohri** [comment]
@deargle can psiTurk be used outside of mechanical turk? I'm using mturk to collect data and our team occasionally has some bandwidth to tag things ourselves. I would be interested in running small subsets of the larger experiment internally

**Comment by deargle** [comment]
Yes. https://github.com/NYUCCL/psiTurk/issues/312#issuecomment-378258001
