### ISSUE TITLE
"Source map error" when running Stroop example experiment on Firefox

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#308]
This is the error that appears in the Firefox console:

```
Source map error: request failed with status 404
Resource URL: http://0.0.0.0:22362/static/lib/jquery-min.js
Source Map URL: jquery-1.10.2.min.map
```

I don't know if it's related, but above this, I'm also getting:

```
Synchronous XMLHttpRequests on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ [jqury-min.js:6:17960]
```

**Comment by jacob-lee** [comment]
psiturk.js preloads images synchronously. maybe that can be revisited using
a promise interface instead.

I've recently begun seeing the source map issue as well, likely because of
changes in firefox dev tools; however, its not a big deal. For efficiency,
minified javascript files are used (jquery-min.js); the source map is just
a way for developer tools to show the original un-minified source when a
developer tool is open. You can either turn off the option in your dev
tool, or add jquery-1.10.2.min.map to the static/lib/ folder.

**Comment by deargle** [comment]
I prefer the synchronous image loading for experiments -- I think that's on purpose. It may not be user-friendly for a consumer-oriented website, but for an experiment, I want there to be no delay when I need to show an image to a participant -- especially if I'm tracking reaction time. I can't easily know how long it takes to download images of various sizes mid-task and account for that in the reaction time metric.
