### ISSUE TITLE
Problems with getting preloadimages() to work properly

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#316]
I'm using the `psiTurk.preloadImages()` command in order to proload images that I'll use later in the experiment. I'm loading them at the parent level, before anything else happens, in my `task.js` file, which is ran in my `exp.html` file. However, I've had complaints from participants with images not loading in time (the images are presented in a sequential fashion with a certain time in between them).

I'm running the whole thing on Heroku, and I can't see any overload issues there. Even if that was the case, there are several minutes from the start of the experiment until the first batch of images are shown, so there should be plenty of time for the client to load them up.

I've been Duckduckgoing around, and preloading of images doesn't seem to be an exact science. Is it simply possible that some browser/computer combinations throws away the preloaded images before they are used? Is there anyway I could tell this is the case? All of my images weights in at 8.3 MB in total.

Also, up until now, I've been making several calls with the `psiTurk.preloadImages()` command, something that I've refactored now so that only one single call is made, using a larger array. However, this really shouldn't make any difference since the function just iterates through each item in an array and creates a new object.

```
/*  PUBLIC METHODS: */
	self.preloadImages = function(imagenames) {
		$(imagenames).each(function() {
			image = new Image();
			image.src = this;
		});
};
```

One long shot, and excuse me if this is wrong: Wouldn't each new iteration of the function above overwrite the previous iteration's variable assignment since the variable `image` always is the same? I'm thinking along the lines that the browser will be more generous with keeping the image around if there's a global variable currently holding it.

When testing the experiment locally on Firefox, I can go to `about:cache` and see that the images have been loaded to disk and stays throughout the experiment. However, they all have an expires time that is set to 10 seconds after they're created. I guess what's happening is that some computer/browser combinations throws out the cached images because they are running low on resources or just have idiosyncratic ways of dealing with cached images. 

Any thought on this? Is it possible to build a more robust preloading function? Is there something I can do in my experiment to decrease the risk of running into problems?

**Comment by deargle** [comment]
> I'm running the whole thing on Heroku, and I can't see any overload issues there. 

If you're using tons and tons of images, you will want to put nginx in front of gunicorn (the psiturk server), and have nginx serve the images directly instead of asking gunicorn to do it every time. Every request made to gunicorn ties up its workers so that they can't respond until they're done -- they're sync workers. I know that there are solutions for nginx in front of gunicorn on heroku, but I haven't tried them yet. The minimal built-in buffering that I get from the built-in heroku router is good enough for my purposes.

> Wouldn't each new iteration of the function above overwrite the previous iteration's variable assignment since the variable image always is the same?

The important part is `image.src = this`, which tells the browser to load the image, and cross-your-fingers cache it. Doesn't matter if the src gets written over later, what matters is that the browser made the request for the image.

> However, they all have an expires time that is set to 10 seconds after they're created.

Have you seen anything about how to increase the cache timeout for images?

**Comment by deargle** [comment]
Closing because stale
