### ISSUE TITLE
Possible timezone issue: Error when expiring HIT

### ISSUE THREAD

**Issue by fohria** [NYUCCL/psiTurk#354]
Seems to be a slight miscalculation somewhere in the code when expiring a HIT:

`[psiTurk server:on mode:sdbx #HITs:5]$ hit expire 37AQKJ12TYJWWNOM8KUXFE0Y0WXTT4`
`Failed to expire HIT. Please check the ID and try again.`
`An error occurred (ParameterValidationError) when calling the UpdateExpirationForHIT operation: The value -80295 is invalid for ExpirationIncrementInSeconds. Valid values range from 60 to 31536000. (1561408989790 s)`

Screenshot where the HITid can be seen:

![Screen Shot 2019-06-24 at 21 48 15](https://user-images.githubusercontent.com/8695061/60051140-3ea3e780-96ca-11e9-9915-35e983d3bf80.png)

This is sandbox mode though, if that matters

**Comment by deargle** [comment]
What version psiturk are you using?

**Comment by fohria** [comment]
Ah, sorry, it's psiturk version 2.3.0 and I'm in UK timezone

**Comment by deargle** [comment]
Looks like an mturk bug, I'm still reading. https://github.com/aws/aws-sdk-java/issues/1817

**Comment by deargle** [comment]
The new boto api doesn't have a direct "extend hit" call -- instead, it just has a "update expiration for hit" call. It says that if the expiration is in the past, the hit will be expired -- otherwise, it will extend the expiration by the given increment. 

From the error you shared, it looks like the expire call is receiving a time _not_ in the past but _earlier_ than the current expiration, and therefore is trying to extend it... backwards. I'm going to patch our expire call to be further in the past (currently, it looks like it is `datetime.datetime.now()`), which I think will fix the problem.

**Comment by deargle** [comment]
@fohria can you install psiturk from the test-suite branch and confirm that this fixes your problem?

**Comment by deargle** [comment]
I think this should do it:
```
git clone https://github.com/NYUCCL/psiTurk.git
cd psiTurk
git fetch origin
git checkout -b test-suite origin/test-suite
pip install -e .
```

**Comment by fohria** [comment]
created a new sandbox hit for 24h, hit expire worked fine!
