### ISSUE TITLE
python2.7 support

### ISSUE THREAD

**Issue by jacob-lee** [NYUCCL/psiTurk#367]
Just installed psiturk from github master in a fresh virtualenv using python 2.7, and got this error from pip:

Collecting cmd2==0.9.13 (from PsiTurk==2.3.2)
  ERROR: Could not find a version that satisfies the requirement cmd2==0.9.13 (from PsiTurk==2.3.2) (from versions: 0.6.0.py3, 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.4.1, 0.3.5, 0.3.6, 0.3.7, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.5.1, 0.6.6, 0.6.6.1, 0.6.7, 0.6.8, 0.6.9, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.6.1, 0.8.7rc1, 0.8.7, 0.8.8, 0.8.9)
ERROR: No matching distribution found for cmd2==0.9.13 (from PsiTurk==2.3.2)

However, no such problem for python3

**Comment by deargle** [comment]
Yup, master is python3 only. I have a python2 branch that I am releasing
bug fixes for for psiturj v2.3.x. next major release will be v3.x.x, and
will be python3 only.

**Comment by adamliter** [comment]
@deargle I noticed that you updated the status_msg.txt file to say that versions >= 2.3.3 support Python 3. Was 2.3.2 not fully Python 3 compatible? I'm updating Docker images for psiTurk, and I was setting up 2.3.2 with Python 3, but should I go back to Python 2 for 2.3.2?

If possible, could you please clarify which recent versions of psiTurk (e.g., 2.3.0, 2.3.1., 2.3.2, and 2.3.3) are compatible with which versions of Python?

**Comment by deargle** [comment]
>= 2.3.1 all support python 3, but increments of the third number are bug
fixes. I should have bumped to 2.4.x when I added python3 support, my bad.
Still learning semantic versioning. I admit that the status message is
unclear.

So either use 2.3.0 for "bugfree" non major under the hood refactor of just
python2, or use 2.3.3 with either python2 or python3. Dont use 2.3.1 or
2.3.2 because bugs.

Next major release will be 3.x.x, and will be python 3 only. That will be
released from the master branch. I have a python2 branch that i'm using to
release hotfixes for psiturk 2.3.x

**Comment by deargle** [comment]
I updated the status message to be more clear:

```
Due to a recent Amazon API deprecation, you need to install psiturk version 2.3.0 or later.
v2.3.0 is python2 only, while versions of v2.3.x >= v2.3.1 support both python2 and python3.
```
