### ISSUE TITLE
Error during hit creation about JSON object

### ISSUE THREAD

**Issue by tree-pi** [NYUCCL/psiTurk#383]
I am running psiturk 2.3.5 under python 3.5 (somehow python 3.6 or 3.7 won't work at all). When doing ```hit create``` it returns:

```
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: the JSON object must be str, not 'bytes')
``` 

I traced back to create_hit() in aws_services_wrapper.py but don't see anything related with JSON...

**Comment by deargle** [comment]
More info on error messages with 3.6 or 3.7 please?

**Comment by tree-pi** [comment]
Sure! The error is same in 3.6 / 3.7 (anaconda). After start psiturk, whatever the first command I put in (e.g.  ```server on``` or ```mode```), the following error returns and the psiturk quits.
```python(27645,0x7fff8a614380) malloc: *** error for object 0x10b70a120: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6```

**Comment by deargle** [comment]
I'm pretty sure that's a gnureadline error, see https://github.com/NYUCCL/psiTurk/issues/371 , because gnureadline is compiled C and that is a C error message. I am going to guess that at some point, gnureadline got installed into your conda env, and is messing things up. You should remove it and let anaconda handle its own readline.

And I just realized that I forgot to make a new pip release with that fix. Hold on, I'll release 2.3.6

**Comment by deargle** [comment]
Okay, try 2.3.6 in a clean environment.

**Comment by tree-pi** [comment]
ok great! ```pip uninstall gnureadline``` then installed psiturk 2.3.6 in conda python 3.7. Everything works now

**Comment by deargle** [comment]
Hooray!
