### ISSUE TITLE
config.txt: public experiments, private/heroku-specific Server Parameters?

### ISSUE THREAD

**Issue by WillForan** [NYUCCL/psiTurk#414]
I've an experiment tracked with git and pushed both to heroku and github. I think I want to keep config.txt in the repo (The instance running on heroku panic if it's not there?) but I don't want the secrets to be public.

I thought I could  use `custom.py` + env variables to overwrite parameters in `config.txt`. But that isn't loaded before the server is running(?). Is there already a way to set heroku specific server info?

```
# from 'host','port','login_username','login_pw','secret_key'
# to   'PSI_HOST' 'PSI_PORT' 'PSI_LOGIN_USERNAME' 'PSI_LOGIN_PW' 'PSI_SECRET_KEY'
for server_setting in config['Server Parameters']:
    envvar='PSI_' + server_setting.upper()
    envval=os.environ.get(envvar)
    if envval:
        config['Server Parameters'][server_setting] = envval
```

**Comment by deargle** [comment]
You're running on master (dev branch), yeah? I have a desire to overhaul the setting of config vars -- to make more (all?) settable - overrideable via env vars.

The heroku instance will not panic, because the way that configparser works, is to first load all of the defaults, and then to override the defaults with settings from a project's config.txt. The only thing that heroku would balk about is that they set `$PORT` that web dynos _have_ to bind to in order to receive traffic. I don't know whether `$HOST` matters, whether it's 127.0.0.1 or 0.0.0.0. But heroku puts a proxy server in front of the gunicorn instance that is launched.

What are you using the login_username, login_pw, and secret_key for? I think that secret_key is basically unused IIRC but I could be way wrong, but otherwise it is used by flask for something or other for when it does secret stuff that we're not doing. login_username and login_pw I definitely want to make env-able, _in addition_ to which I want to perhaps only be setting a hash of the password.  As a safer default for users of psiturk who wouldn't know better than to not share their config.txt. But the config.txt often also contains database_url with secrets stored therein, which is another reason not to have a public config.txt. But that is overrideable via DATABASE_URL env var, because that's what heroku sets when the postgresql addon is... added on.

If we store the login_pw in the config.txt, passwords could be set by some command-line tools that accept plaintext input and then output a hashed secret, I think it's ansible-vault or something like that. But even then, yes it'd be better to override some things with env vars.

I like Flask's CLI approach, it's similar to what you have done in your example. If you want to set the --port flag for `flask run`, you would set `FLASK_RUN_PORT`, format `FLASK_{cmd}_{arg}`.

Are you using the dashboard btw that needs the `login_username` and `login_pw`? How do you like it? That's my bebe.

**Comment by WillForan** [comment]
I only glanced at the dashboard. It seems like it will be very useful when we start piloting in house!

I'm not attached to anything yet, and could go without web facing features needing auth. I'm just worried I'll accidentally leaving some information accessible to someone/bot with a keen eye for config files hosted on github.

I'm not versed enough in cloud environments to know the security implications (do dynos leak `env`? ) . But heroku config:set keeps things out of public repos and is easy to run :)

Thanks again for the quick replies!!

**Comment by deargle** [comment]
The only way that I know of to set an env var on heroku is to do
config:set. They're assumed to be secure. They're scoped to a heroku app.
If they are world-readable, then that would be a security hole in an
otherwise-presumed-secure heroku product.

**Comment by deargle** [comment]
Psiturk 3 now lets any config be set via env var :tada:
