### ISSUE TITLE
MTurkers Still Able To Accept HITs when I'm in Sandbox Mode

### ISSUE THREAD

**Issue by lchen64** [NYUCCL/psiTurk#535]
Also, I can't find my own HIT on my MTurk worker account, even though they are still able to accept it. I guess this is because they have a way of automatically accepting HITs as in the FAQs? Expiring and deleting doesn't work either, because the task is run through my Heroku app so they can continue to accept HITs. Any ideas for the causes of this?

Thanks!!

**Comment by deargle** [comment]
Closing because not a psiturk bug. I think you have some fundamental psiturk infrastructure misunderstandings. 

The mode of the psiturk shell _at the time of creating the hit_ determines whether the published hit is sandbox or live.

> Expiring and deleting doesn't work either, because the task is run through my Heroku app so they can continue to accept HITs.

That's not how it works. The HITS exist on amazon servers. You can use the psiturk shell to expire those hits. Your app will continue to be hosted on heroku, but workers won't be able to perform it for pay if there aren't any HITS they can accept that point to your heroku app.

Repeated, HITS just _point to your heroku url_. HITS are created using the psiturk shell, and they can be expired using the shell, too.
