### ISSUE TITLE
Error creating HIT in psiTurk 2.3.12

### ISSUE THREAD

**Issue by subtrex** [NYUCCL/psiTurk#565]
I have been trying to create a HIT on AMT Developer Sandbox using the "hit create" command in psiTurk 2.3.12, which throws the following error.

Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: An error occurred (RequestError) when calling the CreateHITType operation: This user is not authorized to perform the requested operation. (1720211100160 s))

The "hit create" command was working in the same settings a few days back and nothing has been changed, the configuration files have not been touched. I am happy to provide any other technical details which I might have missed. Any help on the matter would be appreciated.

**Comment by RhtK07** [comment]
Facing the similar issue.
I was using PsiTurk (version 2.3.12) to host my experiment successfully in the past year(2023). However, recently when I tried to host the experiment again(especially this year), I encountered the same(mentioned below) error repeatedly. I have tried various solutions suggested across different discussion groups, but none of them have worked. Posting here is my last resort in seeking a resolution.

Error Is.
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: HTTPSConnectionPool(host='api.psiturk.org', port=443): Max retries exceeded with url: /api/ad (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd83032d1f0>: Failed to establish a new connection: [Errno 110] Connection timed out')))

I would appreciate any help or suggestions to resolve this issue.

**Comment by jacob-lee** [comment]
Does this happen in the sandbox too?

**Comment by RhtK07** [comment]
For me, yes.

**Comment by gureckis** [comment]
sorry 2.x is not supported anymore.  for about 2 years now the psiturk.org website has a message saying all psiturk-org services were being sunsetted.  see the [migration guide](https://psiturk.readthedocs.io/en/latest/migrating.html)
